name: Plan changes
on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_STORAGE: tkubicastore
          TF_CONTAINER: tfstate
          TF_KEY: tf-azure-firewall-rules
        working-directory: terraform
        run: |
          terraform init \
            -backend-config storage_account_name=$TF_STORAGE \
            -backend-config container_name=$TF_CONTAINER \
            -backend-config key=$TF_KEY

      - name: Terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_STORAGE: tkubicastore
          TF_CONTAINER: tfstate
          TF_KEY: tf-azure-firewall-rules
        working-directory: terraform
        run: |
          terraform plan \
            -out=../tfplan
            -backend-config storage_account_name=$TF_STORAGE \
            -backend-config container_name=$TF_CONTAINER \
            -backend-config key=$TF_KEY

      - name: Store plan as artefact
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan  
